libreame_backend:
    resource: "@LibreameBackendBundle/Resources/config/routing.yml"
    prefix:   /

ex4play_ingresarSistema:
    pattern:  /ingreso
    defaults: { _controller: LibreameBackendBundle:Games:servicio, _format: json}
    methods: [POST] 

ex4play_confirmarRegistro:
    pattern:  /registro/{id}
    defaults: { _controller: LibreameBackendBundle:Registro:confirmarRegistro}
    methods: [GET] 
