Libreame\BackendBundle\Entity\Calificatrato:
    type: entity
    table: calificatrato
    indexes:
        fk_calificatrato_tratoaccion1_idx:
            columns:
                - calificatrato_idtrato
        fk_calificatrato_usuario1_idx:
            columns:
                - calificatr_usrcalifica
        fk_calificatrato_usuario2_idx:
            columns:
                - calificatr_usrcalificado
    id:
        idcalificatrato:
            type: bigint
            nullable: false
            options:
                unsigned: false
                comment: "Id del registro de calificación del trato\n"
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecalifica:
            type: datetime
            nullable: false
            options:
                comment: "Fecha en que se realiza la calificación\n"
        idtrato:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 'Id del trato que se califica'
        incalificacion:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Cantidad de estrellas de la calificacion'
        txobservacioncalifica:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
                comment: 'Observacion de la calificacion'
    manyToOne:
        calificatratotrato:
            targetEntity: Trato
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                calificatrato_idtrato:
                    referencedColumnName: idtrato
            orphanRemoval: false
        calificatrUsrcalifica:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                calificatr_usrcalifica:
                    referencedColumnName: idusuario
            orphanRemoval: false
        calificatrUsrcalificado:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                calificatr_usrcalificado:
                    referencedColumnName: idusuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
