<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sesion extends \Libreame\BackendBundle\Entity\Sesion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'insesion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'txsesnumero', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'insesactiva', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'fesesfechaini', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'fesesfechafin', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'txipaddr', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'sesionusuario');
        }

        return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'insesion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'txsesnumero', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'insesactiva', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'fesesfechaini', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'fesesfechafin', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'txipaddr', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Sesion' . "\0" . 'sesionusuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sesion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getinsesion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getinsesion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getinsesion', array());

        return parent::getinsesion();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxsesnumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxsesnumero', array());

        return parent::gettxsesnumero();
    }

    /**
     * {@inheritDoc}
     */
    public function getinsesactiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getinsesactiva', array());

        return parent::getinsesactiva();
    }

    /**
     * {@inheritDoc}
     */
    public function getfesesfechaini()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getfesesfechaini', array());

        return parent::getfesesfechaini();
    }

    /**
     * {@inheritDoc}
     */
    public function getfesesfechafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getfesesfechafin', array());

        return parent::getfesesfechafin();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxipaddr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxipaddr', array());

        return parent::gettxipaddr();
    }

    /**
     * {@inheritDoc}
     */
    public function getsesionusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getsesionusuario', array());

        return parent::getsesionusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function settxsesnumero($txsesnumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxsesnumero', array($txsesnumero));

        return parent::settxsesnumero($txsesnumero);
    }

    /**
     * {@inheritDoc}
     */
    public function setinsesactiva($insesactiva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setinsesactiva', array($insesactiva));

        return parent::setinsesactiva($insesactiva);
    }

    /**
     * {@inheritDoc}
     */
    public function setfesesfechaini($fesesfechaini)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfesesfechaini', array($fesesfechaini));

        return parent::setfesesfechaini($fesesfechaini);
    }

    /**
     * {@inheritDoc}
     */
    public function setfesesfechafin($fesesfechafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfesesfechafin', array($fesesfechafin));

        return parent::setfesesfechafin($fesesfechafin);
    }

    /**
     * {@inheritDoc}
     */
    public function settxipaddr($txipaddr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxipaddr', array($txipaddr));

        return parent::settxipaddr($txipaddr);
    }

    /**
     * {@inheritDoc}
     */
    public function setsesionusuario($sesionusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setsesionusuario', array($sesionusuario));

        return parent::setsesionusuario($sesionusuario);
    }

}
