<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Calificatrato extends \Libreame\BackendBundle\Entity\Calificatrato implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'idcalificatrato', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'fecalifica', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'idtrato', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'incalificacion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'txobservacioncalifica', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'calificatratotrato', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'calificatrUsrcalifica', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'calificatrUsrcalificado');
        }

        return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'idcalificatrato', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'fecalifica', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'idtrato', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'incalificacion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'txobservacioncalifica', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'calificatratotrato', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'calificatrUsrcalifica', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Calificatrato' . "\0" . 'calificatrUsrcalificado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Calificatrato $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getidcalificatrato()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getidcalificatrato();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getidcalificatrato', array());

        return parent::getidcalificatrato();
    }

    /**
     * {@inheritDoc}
     */
    public function getfecalifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getfecalifica', array());

        return parent::getfecalifica();
    }

    /**
     * {@inheritDoc}
     */
    public function getidtrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getidtrato', array());

        return parent::getidtrato();
    }

    /**
     * {@inheritDoc}
     */
    public function getincalificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getincalificacion', array());

        return parent::getincalificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxobservacioncalifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxobservacioncalifica', array());

        return parent::gettxobservacioncalifica();
    }

    /**
     * {@inheritDoc}
     */
    public function getcalificatratotrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcalificatratotrato', array());

        return parent::getcalificatratotrato();
    }

    /**
     * {@inheritDoc}
     */
    public function getcalificatrUsrcalifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcalificatrUsrcalifica', array());

        return parent::getcalificatrUsrcalifica();
    }

    /**
     * {@inheritDoc}
     */
    public function getcalificatrUsrcalificado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcalificatrUsrcalificado', array());

        return parent::getcalificatrUsrcalificado();
    }

    /**
     * {@inheritDoc}
     */
    public function setfecalifica($fecalifica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfecalifica', array($fecalifica));

        return parent::setfecalifica($fecalifica);
    }

    /**
     * {@inheritDoc}
     */
    public function setidtrato($idtrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setidtrato', array($idtrato));

        return parent::setidtrato($idtrato);
    }

    /**
     * {@inheritDoc}
     */
    public function setincalificacion($incalificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setincalificacion', array($incalificacion));

        return parent::setincalificacion($incalificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function settxobservacioncalifica($txobservacioncalifica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxobservacioncalifica', array($txobservacioncalifica));

        return parent::settxobservacioncalifica($txobservacioncalifica);
    }

    /**
     * {@inheritDoc}
     */
    public function setcalificatratotrato($calificatratotrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcalificatratotrato', array($calificatratotrato));

        return parent::setcalificatratotrato($calificatratotrato);
    }

    /**
     * {@inheritDoc}
     */
    public function setcalificatrUsrcalifica($calificatrUsrcalifica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcalificatrUsrcalifica', array($calificatrUsrcalifica));

        return parent::setcalificatrUsrcalifica($calificatrUsrcalifica);
    }

    /**
     * {@inheritDoc}
     */
    public function setcalificatrUsrcalificado($calificatrUsrcalificado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcalificatrUsrcalificado', array($calificatrUsrcalificado));

        return parent::setcalificatrUsrcalificado($calificatrUsrcalificado);
    }

}
