<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Plansuscripcion extends \Libreame\BackendBundle\Entity\Plansuscripcion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'idplansuscripcion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'txnomplan', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'txdescripcionplan', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'fevigencia', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'ingratis', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'inmesesplan', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'dbvalsuscripcion');
        }

        return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'idplansuscripcion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'txnomplan', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'txdescripcionplan', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'fevigencia', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'ingratis', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'inmesesplan', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Plansuscripcion' . "\0" . 'dbvalsuscripcion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Plansuscripcion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getidplansuscripcion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getidplansuscripcion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getidplansuscripcion', array());

        return parent::getidplansuscripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxnomplan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxnomplan', array());

        return parent::gettxnomplan();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxdescripcionplan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxdescripcionplan', array());

        return parent::gettxdescripcionplan();
    }

    /**
     * {@inheritDoc}
     */
    public function getfevigencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getfevigencia', array());

        return parent::getfevigencia();
    }

    /**
     * {@inheritDoc}
     */
    public function getingratis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getingratis', array());

        return parent::getingratis();
    }

    /**
     * {@inheritDoc}
     */
    public function getinmesesplan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getinmesesplan', array());

        return parent::getinmesesplan();
    }

    /**
     * {@inheritDoc}
     */
    public function getdbvalsuscripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getdbvalsuscripcion', array());

        return parent::getdbvalsuscripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function settxnomplan($txnomplan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxnomplan', array($txnomplan));

        return parent::settxnomplan($txnomplan);
    }

    /**
     * {@inheritDoc}
     */
    public function settxdescripcionplan($txdescripcionplan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxdescripcionplan', array($txdescripcionplan));

        return parent::settxdescripcionplan($txdescripcionplan);
    }

    /**
     * {@inheritDoc}
     */
    public function setfevigencia($fevigencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfevigencia', array($fevigencia));

        return parent::setfevigencia($fevigencia);
    }

    /**
     * {@inheritDoc}
     */
    public function setingratis($ingratis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setingratis', array($ingratis));

        return parent::setingratis($ingratis);
    }

    /**
     * {@inheritDoc}
     */
    public function setinmesesplan($inmesesplan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setinmesesplan', array($inmesesplan));

        return parent::setinmesesplan($inmesesplan);
    }

    /**
     * {@inheritDoc}
     */
    public function setdbvalsuscripcion($dbvalsuscripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setdbvalsuscripcion', array($dbvalsuscripcion));

        return parent::setdbvalsuscripcion($dbvalsuscripcion);
    }

}
