<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Videojuego extends \Libreame\BackendBundle\Entity\Videojuego implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'idvideojuego', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txnomvideojuego', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'felanzamiento', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'incategvideojuego', 'videojuegoConsola', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txurlinformacion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txobservaciones', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txgenerovideojuego', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'tximagen');
        }

        return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'idvideojuego', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txnomvideojuego', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'felanzamiento', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'incategvideojuego', 'videojuegoConsola', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txurlinformacion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txobservaciones', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'txgenerovideojuego', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Videojuego' . "\0" . 'tximagen');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Videojuego $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getidvideojuego()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getidvideojuego();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getidvideojuego', array());

        return parent::getidvideojuego();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxnomvideojuego()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxnomvideojuego', array());

        return parent::gettxnomvideojuego();
    }

    /**
     * {@inheritDoc}
     */
    public function getfelanzamiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getfelanzamiento', array());

        return parent::getfelanzamiento();
    }

    /**
     * {@inheritDoc}
     */
    public function getincategvideojuego()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getincategvideojuego', array());

        return parent::getincategvideojuego();
    }

    /**
     * {@inheritDoc}
     */
    public function getvideojuegoconsola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getvideojuegoconsola', array());

        return parent::getvideojuegoconsola();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxurlinformacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxurlinformacion', array());

        return parent::gettxurlinformacion();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxobservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxobservaciones', array());

        return parent::gettxobservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function gettxgenerovideojuego()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettxgenerovideojuego', array());

        return parent::gettxgenerovideojuego();
    }

    /**
     * {@inheritDoc}
     */
    public function gettximagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gettximagen', array());

        return parent::gettximagen();
    }

    /**
     * {@inheritDoc}
     */
    public function settxnomvideojuego($txnomvideojuego)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxnomvideojuego', array($txnomvideojuego));

        return parent::settxnomvideojuego($txnomvideojuego);
    }

    /**
     * {@inheritDoc}
     */
    public function setfelanzamiento($felanzamiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfelanzamiento', array($felanzamiento));

        return parent::setfelanzamiento($felanzamiento);
    }

    /**
     * {@inheritDoc}
     */
    public function setincategvideojuego($incategvideojuego)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setincategvideojuego', array($incategvideojuego));

        return parent::setincategvideojuego($incategvideojuego);
    }

    /**
     * {@inheritDoc}
     */
    public function setvideojuegoConsola(\Libreame\BackendBundle\Entity\Consola $videojuegoConsola)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setvideojuegoConsola', array($videojuegoConsola));

        return parent::setvideojuegoConsola($videojuegoConsola);
    }

    /**
     * {@inheritDoc}
     */
    public function settxurlinformacion($txurlinformacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxurlinformacion', array($txurlinformacion));

        return parent::settxurlinformacion($txurlinformacion);
    }

    /**
     * {@inheritDoc}
     */
    public function settxobservaciones($txobservaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxobservaciones', array($txobservaciones));

        return parent::settxobservaciones($txobservaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function settxgenerovideojuego($txgenerovideojuego)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settxgenerovideojuego', array($txgenerovideojuego));

        return parent::settxgenerovideojuego($txgenerovideojuego);
    }

    /**
     * {@inheritDoc}
     */
    public function settximagen($tximagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'settximagen', array($tximagen));

        return parent::settximagen($tximagen);
    }

}
