<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Libreame\BackendBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'idusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txnomusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txnickname', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txmailusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txclaveusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'fecreacionusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'inusuestado', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txusuvalidacion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'usuarioInlugar', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txusuimagen');
        }

        return array('__isInitialized__', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'idusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txnomusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txnickname', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txmailusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txclaveusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'fecreacionusuario', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'inusuestado', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txusuvalidacion', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'usuarioInlugar', '' . "\0" . 'Libreame\\BackendBundle\\Entity\\Usuario' . "\0" . 'txusuimagen');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdusuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', array());

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnomusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnomusuario', array());

        return parent::getTxnomusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnickname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnickname', array());

        return parent::getTxnickname();
    }

    /**
     * {@inheritDoc}
     */
    public function getTxmailusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxmailusuario', array());

        return parent::getTxmailusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getTxclaveusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxclaveusuario', array());

        return parent::getTxclaveusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecreacionusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecreacionusuario', array());

        return parent::getFecreacionusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getInusuestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInusuestado', array());

        return parent::getInusuestado();
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusuvalidacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusuvalidacion', array());

        return parent::getTxusuvalidacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioInlugar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioInlugar', array());

        return parent::getUsuarioInlugar();
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusuimagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusuimagen', array());

        return parent::getTxusuimagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnomusuario($txnomusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnomusuario', array($txnomusuario));

        return parent::setTxnomusuario($txnomusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnickname($txnickname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnickname', array($txnickname));

        return parent::setTxnickname($txnickname);
    }

    /**
     * {@inheritDoc}
     */
    public function setTxmailusuario($txmailusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxmailusuario', array($txmailusuario));

        return parent::setTxmailusuario($txmailusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setTxclaveusuario($txclaveusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxclaveusuario', array($txclaveusuario));

        return parent::setTxclaveusuario($txclaveusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setFecreacionusuario($fecreacionusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecreacionusuario', array($fecreacionusuario));

        return parent::setFecreacionusuario($fecreacionusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setInusuestado($inusuestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInusuestado', array($inusuestado));

        return parent::setInusuestado($inusuestado);
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusuvalidacion($txusuvalidacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusuvalidacion', array($txusuvalidacion));

        return parent::setTxusuvalidacion($txusuvalidacion);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioInlugar(\Libreame\BackendBundle\Entity\Lugar $usuarioInlugar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioInlugar', array($usuarioInlugar));

        return parent::setUsuarioInlugar($usuarioInlugar);
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusuimagen($txusuimagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusuimagen', array($txusuimagen));

        return parent::setTxusuimagen($txusuimagen);
    }

    /**
     * {@inheritDoc}
     */
    public function creaUsuario($pSolicitud, $Lugar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'creaUsuario', array($pSolicitud, $Lugar));

        return parent::creaUsuario($pSolicitud, $Lugar);
    }

}
